name: tests

concurrency:
  group: phpunit-tests-${{ github.ref_name }}
  cancel-in-progress: true

on: ['push', 'pull_request', 'workflow_dispatch']

env:
  ELASTICSEARCH_PORT: 9201

jobs:
  static_code_analysis:
    runs-on: 'ubuntu-24.04'
    name: 'Static code analysis'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Validate composer.json and composer.lock'
        run: composer validate

      - name: 'Install dependencies with Composer'
        uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: 'highest'
          composer-options: '--prefer-dist'

      - name: Check code quality and coding standards
        run: composer check-code

  phpunit:
    needs: [ static_code_analysis ]
    runs-on: 'ubuntu-24.04'
    name: 'PHPUnit (PHP ${{ matrix.php }})'
    timeout-minutes: 30
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental:
          - false
        dependencies:
          - 'highest'
        php:
          - '8.1'
          - '8.4'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'
          coverage: 'pcov'
          tools: 'composer:v2'
          extensions: 'curl, json, openssl'
          ini-values: 'memory_limit=256M'

      - name: 'Install dependencies with Composer'
        uses: 'ramsey/composer-install@v2'
        with:
          dependency-versions: '${{ matrix.dependencies }}'
          composer-options: '--prefer-dist'

      - name: 'Run phpunit tests'
        run: |
          vendor/bin/phpunit --coverage-clover=tests/clover.xml 2>/dev/null

      - name: Upload coverage results to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: tests/clover.xml

#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
#        run: |
#          vendor/bin/php-coveralls --coverage_clover=tests/clover.xml --json_path=tests/coveralls.json -v
